INFO: Starting training:
        Epochs:          10
        Batch size:      1
        Learning rate:   1e-05
        Training size:   14
        Validation size: 1
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: True
C:\Users\ryanx\env\deepsort\lib\site-packages\torch\cuda\amp\grad_scaler.py:115: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
Epoch 1/10:   0%|                                                                                                                                              | 0/14 [00:00<?, ?img/s]C:\Users\ryanx\env\deepsort\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Epoch 1/10:   7%|████████▏                                                                                                          | 1/14 [00:23<05:06, 23.56s/img, loss (batch)=1.31]


Epoch 1/10:  14%|████████████████▍                                                                                                  | 2/14 [00:55<05:41, 28.45s/img, loss (batch)=1.34]

Epoch 1/10:  21%|████████████████████████▋                                                                                          | 3/14 [01:27<05:29, 29.93s/img, loss (batch)=1.29]

Epoch 1/10:  21%|████████████████████████▋                                                                                          | 3/14 [02:01<07:25, 40.53s/img, loss (batch)=1.29]
Traceback (most recent call last):
  File "C:\Users\ryanx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\queues.py", line 247, in _feed
    send_bytes(obj)
  File "C:\Users\ryanx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\ryanx\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 管道正在被关闭。
INFO: Saved interrupt